import { Hct, SchemeTonalSpot, SchemeNeutral, MaterialDynamicColors as C, argbFromHex } from '@material/material-color-utilities';
const roles = ['primary','onPrimary','primaryContainer','onPrimaryContainer','inversePrimary','secondary','onSecondary','secondaryContainer','onSecondaryContainer','tertiary','onTertiary','tertiaryContainer','onTertiaryContainer','background','onBackground','surface','onSurface','surfaceVariant','onSurfaceVariant','surfaceTint','inverseSurface','inverseOnSurface','error','onError','errorContainer','onErrorContainer','outline','outlineVariant','scrim','surfaceBright','surfaceContainer','surfaceContainerHigh','surfaceContainerHighest','surfaceContainerLow','surfaceContainerLowest','surfaceDim','primaryFixed','primaryFixedDim','onPrimaryFixed','onPrimaryFixedVariant','secondaryFixed','secondaryFixedDim','onSecondaryFixed','onSecondaryFixedVariant','tertiaryFixed','tertiaryFixedDim','onTertiaryFixed','onTertiaryFixedVariant'];
const palettes = [['VIOLET','#6750A4','tonal'],['OCEAN','#0B57D0','tonal'],['JADE','#00897B','tonal'],['FOREST','#386A20','tonal'],['SUNSET','#E8710A','tonal'],['SAKURA','#B4436C','tonal'],['GRAPHITE','#5F6368','neutral']];
const contrasts = [0, 0.5, 1.0];
const hex = n => '0x' + (n >>> 0).toString(16).toUpperCase().padStart(8, '0');
let out = [];
out.push('// GENERATED by material-color-utilities 0.3.0 (SchemeTonalSpot / SchemeNeutral). Do not edit.');
out.push('package dev.ai.elements.ui.theme\n');
out.push('/** Role order of each generated scheme; see [schemeOf]. */');
out.push('internal val SchemeRoles = listOf(' + roles.map(r => `"${r}"`).join(', ') + ')\n');
out.push('/** [palette][dark 0/1][contrast 0/1/2] → ARGB per role in [SchemeRoles] order. */');
out.push('internal val GeneratedSchemes: Array<Array<Array<LongArray>>> = arrayOf(');
for (const [name, seed, kind] of palettes) {
  out.push(`    // ${name} ${seed}`);
  out.push('    arrayOf(');
  for (const dark of [false, true]) {
    out.push('        arrayOf(');
    for (const c of contrasts) {
      const hct = Hct.fromInt(argbFromHex(seed));
      const s = kind === 'neutral' ? new SchemeNeutral(hct, dark, c) : new SchemeTonalSpot(hct, dark, c);
      const vals = roles.map(r => hex(C[r].getArgb(s)));
      out.push('            longArrayOf(' + vals.join(', ') + '),');
    }
    out.push('        ),');
  }
  out.push('    ),');
}
out.push(')');
console.log(out.join('\n'));
